components/html/src/elements/html_script_element.rs
components/html/src/tree_builder/mod.rs
components/html/src/tree_builder/stack_of_open_elements.rs

PR support for other main insert mode. We will skip table mode for now and do more testing of the current code

Implementing support for other main insert mode

---

.vscode/launch.json
Cargo.lock
README.md
components/css/src/cssom/css_rule_list.rs
components/css/src/cssom/style_rule.rs
components/css/src/cssom/stylesheet.rs
components/css/src/lib.rs
components/css/src/selector/mod.rs
components/css/src/selector/structs.rs
components/css/src/values/color.rs
components/css/src/values/mod.rs
components/dom/src/dom_ref.rs
components/dom/src/dom_token_list.rs
components/dom/src/element.rs
components/io/src/data_stream.rs
components/io/src/input_stream.rs
components/style/Cargo.toml
components/style/src/lib.rs
components/style/src/selector_matching.rs
components/style/src/style_tree.rs
components/style/src/test_utils.rs
components/style/src/values/color.rs
components/style/src/values/display.rs
components/style/src/values/mod.rs

This PR support style tree & building style tree

Style tree building

---

Cargo.lock
README.md
components/css/src/cssom/style_rule.rs
components/css/src/parser/structs.rs
components/css/src/selector/mod.rs
components/css/src/selector/structs.rs
components/style/Cargo.toml
components/style/src/inheritable.rs
components/style/src/lib.rs
components/style/src/render_tree.rs
components/style/src/style_tree.rs
components/style/src/value_processing.rs
components/style/src/values/color.rs
components/style/src/values/display.rs

This PR support style value processing
https://www.w3.org/TR/css3-cascade/#value-stages

Style value processing

---

components/style/src/computes/color.rs
components/style/src/render_tree.rs
components/style/src/value_processing.rs
components/style/src/values/color.rs
components/style/src/values/display.rs
components/style/src/values/length.rs
components/style/src/values/mod.rs
components/style/src/values/number.rs
components/style/src/values/percentage.rs

This PR support cache style sharing so we don't have to store separate style values or all dom nodes.

Cache style optimization

---

components/style/src/expand/margin.rs
components/style/src/expand/mod.rs
components/style/src/lib.rs
components/style/src/render_tree.rs
components/style/src/value_processing.rs
components/style/src/values/color.rs
components/style/src/values/display.rs
components/style/src/values/length.rs
components/style/src/values/number.rs
components/style/src/values/percentage.rs

This PR support short-hand properties

CSS Short-hand properties

---

components/layout/src/box_gen.rs
components/layout/src/box_layout.rs
components/layout/src/box_model.rs
components/layout/src/layout_box.rs
components/layout/src/lib.rs
components/style/src/value_processing.rs
components/style/src/values/length.rs
components/test_utils/src/lib.rs
components/test_utils/src/printing.rs

This PR support box width calculation

Box width calculation

---

components/painting/src/display_list.rs
rendering/fixtures/test.html
rendering/src/main.rs

This PR fixed the missing padding bug & switch to `content-box` box-sizing.

Fixed missing padding height when there's no height present

---

.github/workflows/rust.yml
Cargo.lock
Cargo.toml
Makefile.toml
docker/Dockerfile.ubuntu
rendering/Cargo.toml

This PR add dockerfile for ubuntu

Add docker

---

components/layout/src/box_layout.rs
components/layout/src/box_model.rs
components/layout/src/layout_box.rs
components/painting/src/render.rs

This PR changed the content area position. I mistaken the padding box position for the content box position.

Fix for content area

---

components/dom/src/element.rs
components/dom/src/node.rs
components/html/src/element_factory.rs
components/html/src/elements/html_anchor_element.rs
components/html/src/elements/html_base_element.rs
components/html/src/elements/html_marquee_element.rs
components/html/src/elements/html_script_element.rs
components/html/src/elements/html_title_element.rs
components/html/src/elements/mod.rs
components/html/src/tokenizer/token.rs
components/html/src/tree_builder/list_of_active_formatting_elements.rs
components/html/src/tree_builder/mod.rs
components/html/src/tree_builder/stack_of_open_elements.rs

This PR support more html5 elements.
It also do some refactoring to the element factory & element attribute getter.
It also mess up the adoption agency algorithm so if something broke, this is the culprit.

More html5 elements

---

components/html/src/tree_builder/mod.rs

Fixed error when we change the attribute map into a struct

fixed attribute map move error

---

Cargo.lock
Cargo.toml
components/style/Cargo.toml
components/style/src/render_tree.rs
components/tree/Cargo.toml
components/tree/src/lib.rs

Since we will use the tree structure with a reference to the parent
in quite many places across the browser, I created a tree structure
for the need of tree in the future.

Add new tree library

---

components/style/src/values/color.rs
components/style/src/values/number.rs

This PR refactor the CSS color parsing & support hex color

Support more CSS color

---

Cargo.lock
Cargo.toml
components/url/Cargo.toml
components/url/src/lib.rs

I'm too lazy these day so I'm just implemented a dead simple URL parser that doesn't respect spec at all!

Add dead simple URL library

---

components/layout/src/flow/block.rs
components/layout/src/flow/inline.rs
components/layout/src/formatting_context.rs
components/layout/src/layout_box.rs
components/layout/src/tree_builder.rs
components/painting/src/utils.rs
components/style/src/computes/border_radius.rs
components/style/src/computes/border_width.rs
components/style/src/computes/font_size.rs
components/style/src/computes/margin.rs
components/style/src/computes/mod.rs
components/style/src/computes/padding.rs
components/style/src/tree_builder.rs
components/style/src/value_processing.rs
components/style/src/values/border_width.rs
components/style/src/values/length.rs
components/style/src/values/length_percentage.rs
render/src/frame.rs

The length `to_px` was being called on unsupported value. This fixed the bug.

Fixed invalid length computing

---

components/layout/src/flow/inline.rs
components/layout/src/layout_box.rs
components/shared/src/tree_node.rs
components/style/src/computes/font_size.rs
render/src/html.css

When the IFC performing layout on inline box, it should attempt to travel the sub tree with preorder traversal.

Fixed inline layout preorder tree traversal

---

components/dom/src/document.rs
components/dom/src/elements/html_title_element.rs
fixtures/test_title.html
main/src/render_engine.rs
main/src/state/browser_tab.rs
main/src/ui/mod.rs
render/src/frame.rs
render/src/renderer.rs

Support displaying site's title.

Support displaying title

---

main/src/state/browser_tab.rs
main/src/state/mod.rs
main/src/ui/content_area.rs
main/src/ui/mod.rs

Address https://github.com/ZeroX-DG/moon/issues/100

Introduce context menu in UI & View Source menu item feature

---

components/loader/src/resource_loader.rs
main/src/state/browser_tab.rs
main/src/ui/primary_bar.rs

Invalid URL are now no longer being ignored!

Handle invalid url

---

components/layout/src/layout_box.rs
components/shared/src/primitive/rect.rs
main/src/render_client.rs
main/src/state/browser.rs
main/src/state/browser_tab.rs
main/src/ui/content_area.rs
render/src/engine.rs
render/src/frame.rs
render/src/page.rs

This PR support passing mouse move events from GTK to renderer for handling in page.

Added mouse move tracking for render client

---

components/gfx/src/backend.rs
components/layout/src/flow/block.rs
components/layout/src/layout_box.rs
components/painting/src/display_list.rs
components/painting/src/lib.rs
components/painting/src/painter.rs
components/painting/src/request_builder.rs
components/shared/src/primitive/rect.rs
components/shared/src/primitive/rrect.rs
components/shared/src/tree_node.rs
components/style_types/src/property.rs
components/style_types/src/value.rs
components/style_types/src/values/mod.rs
components/style_types/src/values/overflow.rs
fixtures/test_overflow.html
render/src/frame.rs

This PR support scroll bar rendering. It should:
- Support rendering scroll bar for scrollable content
- Support rendering customised scroll bars (with `-moon-scrollbar` prefix)

Support scroll bar rendering

---

Cargo.lock
components/layout/Cargo.toml
components/layout/src/flow/block.rs
components/layout/src/flow/inline.rs
components/layout/src/flow/line_box.rs
components/layout/src/formatting_context.rs
components/layout/src/layout_context.rs
components/layout/src/lib.rs
render/src/pipeline.rs

Closes https://github.com/ZeroX-DG/moon/issues/126

Decoupled layout & gfx module

---

components/dom/src/node.rs
components/html/src/tree_builder/mod.rs
components/html/src/tree_builder/stack_of_open_elements.rs
fixtures/test_table.html

Closes https://github.com/ZeroX-DG/moon/issues/132

Fixed incorrect implementation of tree builder for table tag
